version: '3.4'

services:
  catalogdb:  
    container_name: catalogdb    
    restart: always
    ports:
      - "27017:27017" 
    #networks:
    #  - mongonetwork 
    volumes:
      - mongo_data:/data/db

  basketdb:  
    container_name: basketdb    
    restart: always
    ports:
      - "6379:6379"
      
  portainer:
    container_name: portainer    
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - portainer_data:/data
      #username admin password admin1234

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSetting:ConnectionString=mongodb://catalogdb"  
      #- "MONGOD_ConnectionString=mongodb://catalogdb"  
    depends_on:
      - catalogdb
    ports:
      - "8000:80"
    #networks:
    #  - mongonetwork
      
    #volumes:
    #  - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

#networks:
#  mongonetwork: {}
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
    depends_on:
      - basketdb
    ports:
      - "8001:80"

